# Generated by Django 3.0.3 on 2020-03-29 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('vladeltsev', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('complectation', models.TextField()),
                ('box', models.TextField()),
                ('model', models.TextField()),
                ('modification', models.TextField()),
                ('pokolenie', models.TextField()),
                ('privod', models.TextField()),
                ('probeg', models.PositiveIntegerField()),
                ('rull', models.TextField()),
                ('sostoyanie', models.TextField()),
                ('type_engine', models.TextField()),
                ('type_kyzov', models.TextField()),
                ('color', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('text', models.TextField()),
                ('cat_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.Marks')),
                ('cat_mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.Mesto')),
            ],
        ),
    ]
