# Generated by Django 3.0.3 on 2020-03-31 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('vladeltsev', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('complectation', models.CharField(max_length=50)),
                ('box', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('modification', models.CharField(max_length=50)),
                ('pokolenie', models.CharField(max_length=50)),
                ('privod', models.CharField(max_length=50)),
                ('probeg', models.PositiveIntegerField()),
                ('rull', models.CharField(max_length=50)),
                ('sostoyanie', models.CharField(max_length=50)),
                ('type_engine', models.CharField(max_length=50)),
                ('type_kyzov', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('href', models.CharField(max_length=100)),
                ('image_href_0', models.CharField(max_length=50)),
                ('image_href_1', models.CharField(max_length=50)),
                ('image_href_2', models.CharField(max_length=50)),
                ('cat_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.Marks')),
                ('cat_mesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.Mesto')),
            ],
        ),
    ]
