# Generated by Django 3.0.3 on 2020-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avto_pred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('vladeltsev', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('complectation', models.CharField(max_length=50)),
                ('box', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('modification', models.CharField(max_length=50)),
                ('pokolenie', models.CharField(max_length=50)),
                ('privod', models.CharField(max_length=50)),
                ('probeg', models.PositiveIntegerField()),
                ('rull', models.CharField(max_length=50)),
                ('sostoyanie', models.CharField(max_length=50)),
                ('type_engine', models.CharField(max_length=50)),
                ('type_kyzov', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('cat_marka', models.CharField(max_length=50)),
                ('cat_mesto', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('href', models.CharField(max_length=100)),
                ('image_href_0', models.CharField(max_length=50)),
                ('image_href_1', models.CharField(max_length=50)),
                ('image_href_2', models.CharField(max_length=50)),
            ],
        ),
    ]
