# Generated by Django 3.0.3 on 2020-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0002_avto_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto_pred',
            name='price_pred',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
