# Generated by Django 3.0.3 on 2020-03-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0003_auto_20200226_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
