# Generated by Django 3.0.3 on 2020-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0003_auto_20200329_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='href',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avto',
            name='box',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='complectation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='modification',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='pokolenie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='privod',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='rull',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='sostoyanie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='type_engine',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='type_kyzov',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='avto',
            name='vladeltsev',
            field=models.CharField(max_length=30),
        ),
    ]
