# Generated by Django 3.0.3 on 2020-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0004_auto_20200329_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avto',
            name='box',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='complectation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='href',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='avto',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='modification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='pokolenie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='privod',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='rull',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='sostoyanie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='type_engine',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='type_kyzov',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avto',
            name='vladeltsev',
            field=models.CharField(max_length=50),
        ),
    ]
