# Generated by Django 3.0.3 on 2020-03-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0005_auto_20200329_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='avto',
            name='image_href',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
